### ISSUE TITLE
Add reference to this dataset in HTR-United?

### ISSUE THREAD

**Issue by alix-tz** [millawell/ocr-data#3]
Hello! 
Would you be interested in adding the reference to this dataset in HTR-United? It consists of a YML catalog gathering metadata on available datasets mainly for HTR but also for OCR. Your dataset would be an interesting addition. 

We have a form to help generate the metadata : https://htr-united.github.io/document-your-data.html (there is an english version) 

All you would need to do is fill the form, generate a YML file and either post an issue with the information generated with the form to request their addition in HTR-United; or submit a pull request directly.

I'm available if you need more info. :)

Cheers!
Alix

**Comment by millawell** [comment]
yes! :)

**Comment by PonteIneptique** [comment]
Hi :)
We now parse `CITATION.CFF` file on the HTR-United repository and we found an error in your CFF (double double-quotes), please find a proposed fix:

```yaml
cff-version: 1.2.0
message: "If you use the data set, please cite it as below."
authors:
- family-names: "Lassner"
  given-names: "David"
  orcid: "https://orcid.org/0000-0001-9013-0834"
- family-names: "Coburger"
  given-names: "Julius"
- family-names: "Neudecker"
  given-names: "Clemens"
  orcid: "https://orcid.org/0000-0001-5293-8322"
- family-names: "Baillot"
  given-names: "Anne"
  orcid: "https://orcid.org/0000-0002-4593-059X"
title: >
    Data set of the paper "Publishing an OCR ground truth data set for reuse in an unclear copyright setting"
version: 1.1.0
doi: 10.5281/zenodo.4742068
date-released: 2021-05-07
url: "https://github.com/millawell/ocr-data"
```
